import type { SecretRule } from '../types.js';

const PLACEHOLDER_RE = /your[_-]?(api[_-]?)?key|example|dummy|placeholder|xxx+|test[_-]?key|fake|sample|changeme|\*{4,}/i;

function isPlaceholder(match: string): boolean {
  return PLACEHOLDER_RE.test(match);
}

export const rules: SecretRule[] = [
  {
    id: 'secret-openai-key',
    name: 'OpenAI API Key',
    description: 'OpenAI API key detected',
    severity: 'critical',
    category: 'ai',
    pattern: /\bsk-[a-zA-Z0-9]{20}T3BlbkFJ[a-zA-Z0-9]{20}\b|\bsk-proj-[a-zA-Z0-9_\-]{50,}\b|\bsk-[a-zA-Z0-9]{48}\b/g,
    recommendation: 'Rotate this OpenAI API key at platform.openai.com. Use environment variables.',
    references: ['https://platform.openai.com/docs/guides/safety-best-practices'],
    falsePositiveFilter: (match) => isPlaceholder(match),
  },
  {
    id: 'secret-anthropic-key',
    name: 'Anthropic API Key',
    description: 'Anthropic Claude API key detected',
    severity: 'critical',
    category: 'ai',
    pattern: /\bsk-ant-api\d+-[A-Za-z0-9_\-]{86,100}AA\b|\bsk-ant-[A-Za-z0-9_\-]{90,}\b/g,
    recommendation: 'Rotate this Anthropic API key at console.anthropic.com. Use environment variables.',
    falsePositiveFilter: (match) => isPlaceholder(match),
  },
  {
    id: 'secret-huggingface-token',
    name: 'HuggingFace API Token',
    description: 'HuggingFace access token detected',
    severity: 'high',
    category: 'ai',
    pattern: /\bhf_[a-zA-Z0-9]{37,}\b/g,
    recommendation: 'Rotate this HuggingFace token at huggingface.co/settings/tokens.',
    falsePositiveFilter: (match) => isPlaceholder(match),
  },
  {
    id: 'secret-replicate-token',
    name: 'Replicate API Token',
    description: 'Replicate API token detected',
    severity: 'high',
    category: 'ai',
    pattern: /\br8_[a-zA-Z0-9]{37,}\b/g,
    recommendation: 'Rotate this Replicate token at replicate.com/account.',
    falsePositiveFilter: (match) => isPlaceholder(match),
  },
  {
    id: 'secret-openrouter-key',
    name: 'OpenRouter API Key',
    description: 'OpenRouter API key detected',
    severity: 'high',
    category: 'ai',
    pattern: /\bsk-or-v1-[a-zA-Z0-9]{64}\b/g,
    recommendation: 'Rotate this OpenRouter key at openrouter.ai/keys.',
    falsePositiveFilter: (match) => isPlaceholder(match),
  },
  {
    id: 'secret-cohere-key',
    name: 'Cohere API Key',
    description: 'Cohere API key detected',
    severity: 'high',
    category: 'ai',
    pattern: /(?:cohere|COHERE)[_\-.]?(?:api[_\-.]?)?(?:key|token)\s*[=:'"]+\s*['"]?([A-Za-z0-9]{40})['"]?/gi,
    recommendation: 'Rotate this Cohere key at dashboard.cohere.com.',
    falsePositiveFilter: (match) => isPlaceholder(match),
  },
  {
    id: 'secret-stability-key',
    name: 'Stability AI API Key',
    description: 'Stability AI API key detected',
    severity: 'high',
    category: 'ai',
    pattern: /\bsk-[a-zA-Z0-9]{32}(?:[a-zA-Z0-9]{16})?\b(?=.*stability|.*stabilityai)/gi,
    recommendation: 'Rotate this Stability AI key at platform.stability.ai.',
    falsePositiveFilter: (match) => isPlaceholder(match),
  },
  {
    id: 'secret-mistral-key',
    name: 'Mistral API Key',
    description: 'Mistral AI API key detected',
    severity: 'high',
    category: 'ai',
    pattern: /(?:mistral)[_\-.]?(?:api[_\-.]?)?(?:key|token)\s*[=:'"]+\s*['"]?([A-Za-z0-9]{32})['"]?/gi,
    recommendation: 'Rotate this Mistral key at console.mistral.ai.',
    falsePositiveFilter: (match) => isPlaceholder(match),
  },
  {
    id: 'secret-groq-key',
    name: 'Groq API Key',
    description: 'Groq API key detected',
    severity: 'high',
    category: 'ai',
    pattern: /\bgsk_[a-zA-Z0-9]{52}\b/g,
    recommendation: 'Rotate this Groq key at console.groq.com.',
    falsePositiveFilter: (match) => isPlaceholder(match),
  },
  {
    id: 'secret-together-key',
    name: 'Together AI API Key',
    description: 'Together AI API key detected',
    severity: 'high',
    category: 'ai',
    pattern: /(?:together)[_\-.]?(?:api[_\-.]?)?(?:key|token)\s*[=:'"]+\s*['"]?([a-f0-9]{64})['"]?/gi,
    recommendation: 'Rotate this Together AI key at api.together.xyz.',
    falsePositiveFilter: (match) => isPlaceholder(match),
  },
];
