export { scan, scanFile } from './scanner.js';
export { scanGitHistory, scanStagedFiles } from './git-scanner.js';
export { formatOutput, formatText, formatJson, formatSarif, formatGitText } from './reporter.js';
export { ALL_RULES, getRulesByCategory, getRuleById, CATEGORIES } from './rules/index.js';
export { loadBaseline, saveBaseline, createBaseline, filterBaselineFindings, updateBaseline } from './baseline.js';
export { installHook, uninstallHook } from './hook.js';
export { verifyFinding, verifyFindings, canVerify } from './verifier.js';
export type { VerifyResult } from './verifier.js';
export type { SecretRule, SecretFinding, ScanResult, ScanOptions, Severity } from './types.js';
export { shannonEntropy } from './rules/generic.js';
